version: '3.8'

services:
  postgres:
    image: postgres:13.10
    container_name: kittygram-postgres-1
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    container_name: kittygram-backend-1
    env_file: .env
    depends_on:
      - postgres
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    container_name: kittygram-frontend-1
    env_file: .env
    depends_on:
      - backend
    restart: always

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    container_name: kittygram-gateway-1
    ports:
      - "9000:80"  # ← ИЗМЕНЕНО: проброс порта 9000 на 80 внутри контейнера
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data: