version: '3.8'

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend:latest
    env_file: .env
    volumes:
      # Том для статики Django (путь совпадает с STATIC_ROOT в settings.py)
      - backend_static:/app/staticfiles/
      # Том для медиафайлов Django (путь совпадает с MEDIA_ROOT в settings.py)
      - backend_media:/app/media/
    depends_on:
      - postgres
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend:latest
    env_file: .env
    volumes:
      - frontend_static:/app/static
    depends_on:
      - backend
    restart: always
    # Сборка статики при старте
    command: ["sh", "-c", "npm run build && cp -r /app/build/. /app/static/ && tail -f /dev/null"]

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway:latest
    ports:
      - "9000:80"
    volumes:
      # Статика фронтенда
      - frontend_static:/usr/share/nginx/html:ro
      # Статика бэкенда (путь совпадает с alias в nginx.conf)
      - backend_static:/var/html/static/:ro
      # Медиа бэкенда (путь совпадает с alias в nginx.conf)
      - backend_media:/var/html/media/:ro
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
  frontend_static:
  backend_static:
  backend_media: